### ISSUE TITLE
[CodeStyle] do not use capital letters in package names

### ISSUE THREAD

**Issue by karpovk** [team-rocket-trio/csr-system-desktop#1]
csrSysteamDesktop.Controller should be replaced with csrsysteamdesktop.controller and such

**Comment by shreyner** [comment]
Fixed by # https://github.com/team-rocket-trio/csr-system-desktop/commit/1abdccef251374144aaedaefb5428aa5a4e1a734

**Comment by shreyner** [comment]
Fixed by # https://github.com/team-rocket-trio/csr-system-desktop/commit/1abdccef251374144aaedaefb5428aa5a4e1a734
